[project]
name = "modrinth-scrapy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "scrapy>=2.12.0",
    "scrapy-playwright>=0.0.43",
    "tqdm>=4.67.1",
]
